---
- name: Debug Intersight Environment
  hosts: localhost
  gather_facts: false
  tasks:

    - name: Fetch Default Organization MOID
      cisco.intersight.intersight_info:
        api_key_id: "{{ api_key_id }}"
        api_private_key: "{{ api_private_key }}"
        validate_certs: true
      register: org_info

    - name: Print Organization MOID
      debug:
        msg: "The Moid for the 'default' organization is {{ (org_info.intersight_organizations | selectattr('Name', 'equalto', 'default') | first).Moid }}"
      when: org_info.intersight_organizations is defined
